#
# Google Cloud Build Configuration for AdvanceWeekly
#
# This configuration file defines the build and deployment pipeline for
# the AdvanceWeekly application to Google Cloud Run. The pipeline consists of:
#
# 1. Build Stage: Creates a multi-stage Docker image with:
#    - Dependencies layer (optimized for caching)
#    - Build layer (compiles Next.js application)
#    - Runtime layer (minimal production image)
#
# 2. Push Stage: Stores the built image in Google Artifact Registry
#    with both commit-specific and 'latest' tags
#
# 3. Deploy Stage: Deploys the image to Cloud Run with:
#    - Cloud SQL database connection
#    - Secret Manager integration for sensitive variables
#    - Auto-scaling configuration for production workloads
#
# Environment Variables:
# - PROJECT_ID: Google Cloud project ID (auto-populated)
# - BUILD_ID: Unique build identifier (auto-populated)
#
# Prerequisites:
# - Cloud Build API enabled
# - Artifact Registry repository created
# - Cloud SQL instance running
# - Secrets stored in Secret Manager: database-url, openai-api-key
#

timeout: 600s  # 10 minutes max (target: 3-5 minutes)
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # High CPU for fast builds
  env:
    - 'DOCKER_BUILDKIT=1'  # Enable Docker BuildKit for better caching

steps:
  # Fast parallel build approach - skip quality checks in deployment
  # Quality checks handled by GitHub Actions CI before merge

  # Step 1: Build and push Docker image with optimized caching
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-and-push'
    args:
      - 'build'
      - '--target=production'
      - '--cache-from=us-central1-docker.pkg.dev/$PROJECT_ID/advanceweekly-repo/advanceweekly:latest'
      - '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/advanceweekly-repo/advanceweekly:$BUILD_ID'
      - '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/advanceweekly-repo/advanceweekly:latest'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'
    timeout: 360s  # 6 minutes max for build
  
  # Push images in parallel
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-images'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/advanceweekly-repo/advanceweekly'
    waitFor: ['build-and-push']
    timeout: 120s  # 2 minutes for push

  # Step 2: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-cloud-run'
    args:
      - 'run'
      - 'deploy'
      - 'advanceweekly'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/advanceweekly-repo/advanceweekly:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'
      - '--port=8080'
      - '--allow-unauthenticated'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--concurrency=80'
      - '--timeout=300'
      - '--set-env-vars=NODE_ENV=production,NEXT_TELEMETRY_DISABLED=1,NEXTAUTH_URL=https://advanceweekly.io,AUTH_URL=https://advanceweekly.io'
      - '--set-secrets=DATABASE_URL=database-url:latest,OPENAI_API_KEY=openai-api-key:latest,NEXTAUTH_SECRET=nextauth-secret:latest,GOOGLE_CLIENT_ID=google-client-id:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest'
      - '--add-cloudsql-instances=advanceweekly-prod:us-central1:advanceweekly-db'
      - '--execution-environment=gen2'
    waitFor: ['push-images']
    timeout: 120s  # 2 minutes for deployment

  # Step 3: Quick deployment verification
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'verify-deployment'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "✅ Fast deployment completed!"
        echo "🌐 https://advanceweekly.io"
        echo "⚡ Total time: ~3-5 minutes (optimized)"
    waitFor: ['deploy-cloud-run']
    timeout: 15s

# Images to store in Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/advanceweekly-repo/advanceweekly:$BUILD_ID'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/advanceweekly-repo/advanceweekly:latest'

# Substitutions for environment variables (currently unused but defined for future use)
# substitutions:
#   _SERVICE_NAME: 'advanceweekly'
#   _REGION: 'us-central1'