version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "snippets-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket"
s3_prefix = "snippets-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "DatabaseUrl=postgresql://username:password@your-rds-endpoint:5432/snippets_db",
  "JwtSecret=your-jwt-secret-here"
]
image_repositories = []