AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Weekly Snippets Reminder API

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Environment:
      Variables:
        DATABASE_URL: !Ref DatabaseUrl
        JWT_SECRET: !Ref JwtSecret

Parameters:
  DatabaseUrl:
    Type: String
    Description: PostgreSQL database connection string
  JwtSecret:
    Type: String
    Description: JWT secret for authentication
    NoEcho: true

Resources:
  # API Gateway
  SnippetsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # Lambda Functions
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/auth/
      Handler: index.handler
      Events:
        AuthPost:
          Type: Api
          Properties:
            RestApiId: !Ref SnippetsApi
            Path: /auth
            Method: post

  SnippetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/snippets/
      Handler: index.handler
      Events:
        SnippetsGet:
          Type: Api
          Properties:
            RestApiId: !Ref SnippetsApi
            Path: /snippets
            Method: get
        SnippetsPost:
          Type: Api
          Properties:
            RestApiId: !Ref SnippetsApi
            Path: /snippets
            Method: post
        SnippetsPut:
          Type: Api
          Properties:
            RestApiId: !Ref SnippetsApi
            Path: /snippets/{id}
            Method: put
        SnippetsDelete:
          Type: Api
          Properties:
            RestApiId: !Ref SnippetsApi
            Path: /snippets/{id}
            Method: delete

  IntegrationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/integrations/
      Handler: index.handler
      Events:
        IntegrationsGet:
          Type: Api
          Properties:
            RestApiId: !Ref SnippetsApi
            Path: /integrations
            Method: get
        IntegrationsPost:
          Type: Api
          Properties:
            RestApiId: !Ref SnippetsApi
            Path: /integrations
            Method: post

Outputs:
  ApiGatewayEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${SnippetsApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"